name: coocktimer
description: A Flutter project with the aim of creating and managing recipes, and may create also alarms to be able to control the cooking time of them.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.2.5+1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Sriracha
      fonts: 
        - asset: lib/assets/fonts/Sriracha-Regular.ttf

vars: 
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts: 
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
